### ISSUE TITLE
Improvement: Avoid flash of unformated mail body

### ISSUE THREAD

**Issue by dev8765** [grommunio/grommunio-web#13]
I'm on the community-repository on openSUSE-Leap-15.5
grommunio-web-3.7.50.g9e269947-lp155.62.1.noarch

Steps to reproduce (tested with Chrome and Firefox on Win10): 
 - Login into webmail
 - **Single** click in the 2nd column on a mail to open it in the 3rd column
 - There is a short flash with the mail body displayed as raw text in light grey, without any formatting, images are missing
 - The formatted contents of previous opened mails seem to be remembered and there is no flash on reopen
 - But after a **double** click on any mail the flash returns, even for mails that were previously opened
 - Sign out also clears the remembered formatted content

I'm not aware of such a behavior in other webmailers like web.de. 
Maybe there is a chance to improve this.

<img width="333" alt="lade" src="https://github.com/grommunio/grommunio-web/assets/30365427/35caa2f7-d097-4a57-ba98-9d7cae6ead99">

**Comment by jengelh** [comment]
`class.properties.php:getMailProperties` and `getMailListProperties` define proptag lists that effectively define what gets returned for mails and, more importantly, mail lists. Note how `getMailListProperties` unsets some proptags, but `$props['body']` is *not* among them. As a result, function `class.operations.php:getTable`, lines `mapi_folder_getcontentstable` & `mapi_table_queryrows($table, $properties, $start, $rowcount);` will yield a 255-character fragment of PR_BODY (plaintext body). Asking for a HTML fragment is pointless, because the first 255 chars usually are metadata clutter from WYSIWYG editors.

The javascript parts thus have {subject, from, to, date, bodyfragment, a few more} for all mails in memory. Having the fragment is required to implement something like a 3-line view like Outlook, e.g. (the grey portion is PR_BODY):
![1](https://github.com/grommunio/grommunio-web/assets/8861948/617553f5-7573-4fad-9332-1583ebf412d4)
g-web does not support a 1-line or 3-line view like that, so… :shrug: I guess that ain't the reason that $props['body'] was not unset so far.

As you click on a mail, the JS parts use the existing data to fill the reading pane, while at the same time issuing an asynchronous XmlHttpRequest to load the complete PR_BODY/PR_HTML. Once the XHR completes, the reading pane is updated again. The first update of the reading pane with the fragment happens here:

```
# stacktrace
update in /web/client/zarafa/common/ui/messagepanel/MessageBody.js
onSetRecord in /web/client/zarafa/core/plugins/RecordComponentUpdaterPlugin.js
fire in /web/client/extjs/ext-all-debug.js
fireEvent in /web/client/extjs/ext-all-debug.js
setRecord in /web/client/zarafa/core/plugins/RecordComponentPlugin.js
setRecord in /web/client/zarafa/core/ui/PreviewPanel.js
showRecordInPanel in /web/client/zarafa/core/ui/PreviewPanel.js
onPreviewRecordChange in /web/client/zarafa/core/ui/PreviewPanel.js
fire in /web/client/extjs/ext-all-debug.js
fireEvent in /web/client/extjs/ext-all-debug.js
setPreviewRecord in /web/client/zarafa/core/ContextModel.js
onRowSelect in /web/client/zarafa/mail/ui/MailGrid.js
[click on a mail]
```

The original authors called it "preview", which suggests that showing the fragment in the reading pane might actually have been considered a feature, and so, perhaps we *should not* unset $props['body'] after all.

So perhaps a better course of action is to show another "blue info bar" indicating that a preview is being shown.
![2](https://github.com/grommunio/grommunio-web/assets/8861948/6cd5dad5-67f3-49ac-9719-5251975f6274)
